name: Release Notifier

on:
  release:
    types: [published]

jobs:
  post-to-discord:
    name: Post to Discord 📡
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # @see https://github.com/rjstone/discord-webhook-notify
      - uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          color: '#1EE084'
          text: New release from [Quilt](https://github.com/lemonmade/quilt)!
          description: >
            **${{ github.event.release.tag_name }}**

            Published by [${{ github.event.release.author.login }}](${{ github.event.release.author.html_url }})

            ${{ github.event.release.html_url }}
          footer: ${{ github.event.release.published_at }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
